// Test Router ✅
GET http://localhost:8001/api

###

// Test session ✅
GET http://localhost:8001/users

###

// Add new User
POST http://localhost:8001/users
Content-Type: application/json

{
    "username":"Laur",
    "password":"password2"
}

###

//Logging in
POST http://localhost:8001/login
Content-Type: application/json

{
    "username":"Laur",
    "password":"password2"
}

###

// Logging Out

GET http://localhost:8001/logout