POST http://localhost:5000/api/register HTTP/1.1
content-type: application/json

{
  "username": "ash",
  "password": "password"
}
###

POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
  "username": "ash",
  "password": "password"
}
###

GET http://localhost:5000/api/users HTTP/1.1
###

GET http://localhost:5000/api/restricted/topsecret HTTP/1.1
###